webserver:
  localhost: 127.0.0.1 #localhost ip address
  publichost: 127.0.0.1 #localhost ip address
  url: http://127.0.0.1 #server ip address
  port: 4601 #port
  name: libraries
  domain: 127.0.0.1
  
database:
  name: library #databasename
  user: root #username
  password: Emmanuel@100 #postgres password
  port: 5432 #postgresql default port

secret:
  secret: 0ifp5bw(!1j8bq#2bwd24)bn!0$gco6hhoce^!7tmprdaf$1z7

privateKeys:
  - systemName: "library"
    keyPath: "./.storage/keys/library_private_key.pem"

publicKeys:
  - systemName: "library"
    keyPath: "./.storage/keys/library_public_key.pem"


